// Talks to the static JSON files generated by scripts/build-units.mjs.
export interface UnitRow {
  id: number
  name: string
  weight: number
  rate: number
}

export interface RegionInfo {
  region: string // display name, e.g. "Alabama"
  code: string // e.g. "AL"
  slug: string
  file: string
  count: number
}

export async function fetchRegions(): Promise<RegionInfo[]> {
  const res = await fetch('/data/regions.json')
  if (!res.ok) throw new Error(`Failed to load region list (${res.status})`)
  return res.json()
}

// The on-disk shape: field name -> array of values (columnar), not an array
// of {id, name, ...} objects. See scripts/build-units.mjs for why.
interface ShardColumns {
  id: number[]
  name: string[]
  weight: number[]
  rate: number[]
}

export async function fetchShard(file: string): Promise<UnitRow[]> {
  const res = await fetch(`/data/${file}`)
  if (!res.ok) throw new Error(`Failed to load unit data (${res.status})`)
  const shard: ShardColumns = await res.json()
  return shard.id.map((id, i) => ({
    id,
    name: shard.name[i],
    weight: shard.weight[i],
    rate: shard.rate[i],
  }))
}

/**
 * Pick `count` distinct units from `pool`, at random weighted by `weight`.
 * `pool` here is one region's worth of rows (a few hundred, up to ~800) —
 * small enough that a plain linear scan is fast enough. The cumulative-sum
 * + binary-search version would only start to matter at the scale of the
 * full unsharded dataset, which sharding already took off the table.
 */
export function rollWeightedChoices(pool: UnitRow[], count = 3): number[] {
  const remaining = pool.slice()
  const picked: number[] = []

  for (let i = 0; i < count && remaining.length > 0; i++) {
    const totalWeight = remaining.reduce((sum, u) => sum + u.weight, 0)
    let r = Math.random() * totalWeight
    let index = remaining.length - 1 // floating-point fallback

    for (let j = 0; j < remaining.length; j++) {
      r -= remaining[j].weight
      if (r < 0) {
        index = j
        break
      }
    }

    picked.push(remaining[index].id)
    remaining.splice(index, 1)
  }

  return picked
}
